apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: swiggy-app
        image:767397713514.dkr.ecr.us-east-2.amazonaws.com/swiggy
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
